In [ ]:
import numpy as np
np

<module 'numpy' from '/usr/local/python/3.14.2/lib/python3.14/site-packages/numpy/__init__.py'>

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [ ]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [ ]:
a[2]

np.int64(3)

In [ ]:
a[2] = 10

In [ ]:
a

array([ 1,  2, 10,  5,  7, 12])

In [ ]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
n[0,1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
n[0]

array([ 1, 20,  3])

In [ ]:
n[2] = [1,1,1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [ ]:
n[:,1]

array([20,  5,  1])

In [ ]:
n[:]

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [ ]:
n[:,2] = [0,1,2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [ ]:
np.random.seed(10)
100 * np.random.rand(5,2)

array([[77.13206433,  2.07519494],
       [63.36482349, 74.88038825],
       [49.85070123, 22.47966455],
       [19.80628648, 76.05307122],
       [16.91108366,  8.83398142]])

In [ ]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [ ]:
np.random.seed(2)
np.random.randint(low = 0, high = 100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
a + 1

array([1, 2, 3, 4, 5])

In [ ]:
a * 2

array([0, 2, 4, 6, 8])

In [ ]:
a / 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [ ]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [ ]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [ ]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

In [ ]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

In [ ]:
a >= 2

array([False, False,  True,  True,  True])

In [ ]:
a > b

array([False, False,  True,  True,  True])

In [ ]:
a[a>b]

In [ ]:
a.min()